language: r
r:
  - oldrel
  - release
  - devel 
r_check_args: '--ignore-vignettes'
r_build_args: '--no-build-vignettes'
before_install:
  - sudo apt-get install -y libmagick++-dev
  - sudo add-apt-repository -y ppa:opencpu/imagemagick
  - sudo apt-get update
  - sudo apt-get install -y libmagick++-dev             
r_packages:
  - covr
addons:
  apt:
    packages:
      - libtiff-dev
      - libpng-dev
      - libjpeg-dev
      - libfftw3-dev
      - libmagick++-dev
      - librsvg2-dev
      - libwebp-dev
      - libpoppler-cpp-dev
      - libtesseract-dev
      - libleptonica-dev
      - tesseract-ocr-eng
      - r-cran-rgdal
      - libfftw3-dev
      - cargo
cache: packages

after_success:
  - Rscript -e 'covr::coveralls()'
  - Rscript -e 'covr::codecov()'
