# R for travis: see documentation at https://docs.travis-ci.com/user/languages/r

language: r
r:
  - release
  - devel 
r_check_args: '--ignore-vignettes'
r_build_args: '--no-build-vignettes'

r_packages:
  - covr
  - mockery
  - shinytest
  - testthat
  - magick
  - imager
addons:
  apt:
    packages:
      - libtiff-dev
      - libpng-dev
      - libjpeg-dev
      - libfftw3-dev
      - libmagick++-dev
      - librsvg2-dev
      - libwebp-dev
      - libpoppler-cpp-dev
      - libtesseract-dev
      - libleptonica-dev
      - tesseract-ocr-eng
      - r-cran-rgdal
      - libfftw3-dev
      - cargo
cache: packages

after_success:
  - Rscript -e 'covr::codecov()'
