# R for travis: see documentation at https://docs.travis-ci.com/user/languages/r

language: r
r:
  - release
before_install:
  - sudo apt-get install -y libmagick++-dev
  - sudo add-apt-repository -y ppa:opencpu/imagemagick
  - sudo apt-get update
  - sudo apt-get install -y libmagick++-dev 
  - brew install imagemagick@6
  - sudo apt-get install libfftw3-dev libX11-dev libtiff-dev

cache: packages

