# R for travis: see documentation at https://docs.travis-ci.com/user/languages/r

language: r
r:
  - release
  - devel 
r_check_args: '--ignore-vignettes'
r_build_args: '--no-build-vignettes'

r_packages:
  - covr
  - mockery
  - shinytest
  - testthat
  - magick
  - imager

cache: packages

after_success:
  - Rscript -e 'covr::codecov()'
